### ISSUE TITLE
bf16x isnt working

### ISSUE THREAD

**Issue by ImANewUser123** [mayo78/psychenginescripts#3]
![help me](https://user-images.githubusercontent.com/125198255/218315289-710a482f-89b0-4122-bd87-ae1daccc0484.PNG)

it keeps saying this and im not a coder so can you help

**Comment by mayo78** [comment]
thats not an issue with bf16x, its an issue with a different script that uses objectPlayAnimation instead of playAnim, and you also didn't put the image in the right place
